### ISSUE TITLE
Redownloading cdx files

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/commoncrawl-fetcher-lite#47]
Does:

java -jar commoncrawl-fetcher-lite-X.Y.Z.jar FetchIndices fetch-indices-config.json

attempt to re-download existing index files? With all of the problems CC is having these days it's almost impossible to get the index files downloaded. I've restarted a few times but the code seems to start with index 00000 again.

Does the code ignore existing cdx files when restarting?

Thanks.

**Comment by tballison** [comment]
Y, LLMs have destroyed access to CC. :(

The current code does restart without taking into consideration what has already been downloaded. I _thought_ that was a design decision because we can't tell if an index file has been downloaded in its entirety or if it was truncated. Looking at the code, it is more of a limitation on the tika-pipes framework that the list iterator or the fetchers don't have the ability to "figure out" what has already been processed. The burden in that framework is on the user to select what files to process.

Some options:

a) There's a way to specify the literal index files instead of the "lists of index files": e.g. crawl-data/CC-MAIN-2023-06/cc-index.paths.gz. 

b) You could modify your "list of index files" file to exclude the files that have been successfully downloaded

c) We could also add a "startFrom" parameter or an "indexFileMatch", which would be a regex on the indexfile path for whether or not to grab it.

I realize these options are not ideal.

Let me know which direction you'd like to head.

**Comment by gleporeNARA** [comment]
That's what I was assuming. I've got 20 indexes downloaded, would:

java -jar commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar  fetch-files-from-local-indices.json

start going after files in only those downloaded indexes? 

I'm guessing my problems are entirely due to the LLM's hitting CC, so I don't think there's anything you can do on the code end. I looked into downloading directly from the S3 bucket, but that looked too complex.

Thanks.

**Comment by tballison** [comment]
Yes. That absolutely should work. Note that the index files do not contain urls in random order so you will not get a random sample of Common Crawl data by taking the first 20 index files...if that's of any importance for you.

**Comment by gleporeNARA** [comment]
Right, I'll work on it that way. As long as I get octet-stream stuff, I don't really care exactly what stuff. I would, however, like to eventually get a full CC download so we can ascertain if the recently added mime-types to Tika have reduced the identified/unidentified ratio.
